# version: '3.9'

# services:
#   db:
#     image: mysql:latest
#     container_name: tournament_db
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#       MYSQL_DATABASE: gestion_tournois
#     volumes:
#       - tournament_db_data:/var/lib/mysql
#       - ./db/sauvegarde.sql:/docker-entrypoint-initdb.d/sauvegarde.sql
#     networks:
#       - tournament-network
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   backend:
#     image: yacineg/gestiontournois_backend:latest
#     container_name: tournament-backend
#     ports:
#       - "8080:8080"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gestion_tournois?useSSL=false&allowPublicKeyRetrieval=true
#       SPRING_DATASOURCE_USERNAME: root
#       SPRING_DATASOURCE_PASSWORD: ""
#       SPRING_JPA_HIBERNATE_DDL_AUTO: update
#       SPRING_JPA_SHOW_SQL: "true"
#       JWT_SECRET: YourVeryComplexAndLongSecretKeyForHS256AtLeast32Chars
#       JWT_EXPIRATION: "86400000"
#       LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
#       SPRING_PROFILES_ACTIVE: dev
#     networks:
#       - tournament-network
#     depends_on:
#       db:
#         condition: service_healthy
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     restart: unless-stopped

#   frontend:
#     image: yacineg/gestiontournois_frontend:latest
#     container_name: tournament-frontend
#     ports:
#       - "3001:80"
#     environment:
#       - VITE_API_URL=http://tournament-backend:8080
#     networks:
#       - tournament-network
#     depends_on:
#       - backend
#     restart: unless-stopped

# volumes:
#   tournament_db_data:
#     driver: local

# networks:
#   tournament-network:
#     driver: bridge

version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: tournament_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gestion_tournois
    volumes:
      - tournament_db_data:/var/lib/mysql
      - ./db/sauvegarde.sql:/docker-entrypoint-initdb.d/sauvegarde.sql
    networks:
      - tournament-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: yacineg/tournaments_backend:latest
    container_name: tournament-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gestion_tournois?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      JWT_SECRET: YourVeryComplexAndLongSecretKeyForHS256AtLeast32Chars
      JWT_EXPIRATION: "86400000"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - tournament-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    image: yacineg/tournaments_frontend:latest
    container_name: tournament-frontend
    ports:
      - "3001:80"
    environment:
      VITE_API_URL: http://tournament-backend:8080
    networks:
      - tournament-network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  tournament_db_data:
    driver: local

networks:
  tournament-network:
    driver: bridge
